version: "3"

networks:
  ${GITEA_NETWORK}:
    external: false

services:
  server:
    image: gitea/gitea:${GITEA_VERSION}
    container_name: ${GITEA_CONTAINER_NAME}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=${MYSQL_DATABASE_GITEA}
      - GITEA__database__USER=${MYSQL_USER_GITEA}
      - GITEA__database__PASSWD=${MYSQL_PASSWORD_GITEA}
    restart: ${RESTART_FLAG}
    networks:
      - ${GITEA_NETWORK}
    volumes:
      - ${GITEA_BIND_PATH}/gitea:/data
      - ${GITEA_BIND_PATH}/etc/timezone:/etc/timezone:ro
      - ${GITEA_BIND_PATH}/etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_EXPOSED_PORT_HTTP}:3000"
      - "${GITEA_EXPOSED_PORT_SSH}:22"
    depends_on:
      - db

  db:
    image: mariadb/mariadb:${MARIADB_VERSION}
    restart: ${RESTART_FLAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_GITEA}
      - MYSQL_USER=${MYSQL_USER_GITEA}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_GITEA}
      - MYSQL_DATABASE=${MYSQL_DATABASE_GITEA}
    networks:
      - ${GITEA_NETWORK}
    volumes:
      - ${GITEA_BIND_PATH}/mysql:/var/lib/mysql
