# Name: persistent-volume-claim.yaml
# Description: 
# Persistent Volume Claim Configuration file
# for NFS volume via the NFS CIFS driver 
#
# Prerequisites: MicroK8s
#
# Usage:
# Create file and alter the 'storage' line to reflect the amt of NFS storage
# example: 1000Gi #1TB Claim
# microk8s kubectl apply -f - < persistent-volume-claim.yaml
# Project: https://github.com/vintagedon/proxmoxlab/tree/main/bash-scripts
# License: Apache-2.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: XGi #Change 'X' to the # of GBs of NFS storage
